### ISSUE TITLE
Hiển thị song ngữ khi render chương cài đặt.

### ISSUE THREAD

**Issue by nguyenhoa93** [mlbvn/d2l-vn#3069]
### Mô tả lỗi
Khi render chương cài đặt, phần `Cài đặt Framework và Gói thư viện d2l` & `Hỗ trợ GPU` bị hiển thị song ngữ.

### Ảnh chụp màn hình
![img](https://i.imgur.com/nXYswxf.png)

### **Desktop (Vui lòng hoàn thiện thông tin như hướng dẫn):**
 - OS: MacOSX
 - Browser: Chrome
 - Phiên bản: Google Chrome 86.0.4240.75

### **Smartphone (Vui lòng hoàn thiện thông tin như hướng dẫn):**
 - Thiết bị: [Ví dụ: iPhone6]
 - OS: [Ví dụ: iOS 8.1]
 - Browser [Ví dụ: Opera, Safari]
 - Phiên bản [Ví dụ: 22]

### Đường dẫn đến nội dung có lỗi
- https://d2l.aivivn.com/chapter_install/index_vn.html 

### Thông tin thêm
Vui lòng cung cấp thêm bất kỳ thông tin nào bạn tin là hữu ích cho chúng tôi.

**Comment by cuongvng** [comment]
@nguyenhoa93 mình xem file thì thấy các comment `<!-- ... -->` đều đúng cú pháp. Phần này vừa được update thêm các tab pytorch, tensorflow #2318, nhưng bản trên web chưa thấy xuất hiện. Có phải tại chưa build lại phần này không?

**Comment by duythanhvn** [comment]
@cuongvng anh đã "mất việc" rồi sao...

Btw, @nguyenhoa93 cái này mình nghĩ do mình chưa cập nhật với repo gốc và chưa build đủ, mình sẽ check sau. Minor trong hiện tại, anh em focus phần dịch đã nhé.
