### ISSUE TITLE
Lỗi hiển thị markdown dòng 5 từ dưới lên trang 32/965

### ISSUE THREAD

**Issue by giantrule** [mlbvn/d2l-vn#3115]
Phần câu hỏi thường gặp. 
Câu hỏi số 2 không hiển thị đúng. 
ver: 0.14.4
Asset: d2l-vn.pdf

**Comment by duythanhvn** [comment]
Chào bạn,

Cảm ơn phản hồi của bạn, nhóm ghi nhận lỗi này nhé.
