### ISSUE TITLE
Lỗi hiện thị từ ngữ

### ISSUE THREAD

**Issue by nguyenhung1903** [mlbvn/d2l-vn#3117]
### Mô tả lỗi
Lỗi hiện thị từ ngữ tại v0.14.4 (Bản In)
### Mô tả thêm
Em vừa mới đọc qua phát hiện một số lỗi hiển thị từ bị mất, hoặc khuyết đi các kí tự.
### Ảnh chụp màn hình
Phần 1. Cài Đặt:
![image](https://user-images.githubusercontent.com/42035568/105165940-878f7c80-5b49-11eb-9d20-69758540a88b.png)

Trang 6:
![image](https://user-images.githubusercontent.com/42035568/105165589-18198d00-5b49-11eb-9413-95875ea92834.png)

Trang 21
![image](https://user-images.githubusercontent.com/42035568/105165712-44cda480-5b49-11eb-9fa5-4113c67c222b.png)

Trang 26:
![image](https://user-images.githubusercontent.com/42035568/105165460-f4564700-5b48-11eb-83cc-ddc17fa3faca.png)

**Comment by nguyenhung1903** [comment]
Trang 99: 
Desktop: lỗi Not Supported by viewer
![image](https://user-images.githubusercontent.com/42035568/105167991-0d142c00-5b4c-11eb-9320-4499e64d7db4.png)

**Comment by duythanhvn** [comment]
Chào bạn,

Cảm ơn bạn đã gửi thông tin. Nhóm sẽ cập nhật lại Fig 5.1.3 trong thời gian tới như mô tả của bạn ở trên, về phần bản in thì tôi chưa rõ nguyên nhân vì bản digital không có bị thiếu thông tin như mô tả, tôi đoán chừng việc này có thể liên quan đến trình đọc pdf ở bên đơn vị in nên nếu được nhờ bạn kiểm tra lại giúp tôi nhé.
