### ISSUE TITLE
Connecting with d2l developers

### ISSUE THREAD

**Issue by mli** [mlbvn/d2l-vn#3126]
Hi Guys,

Thanks a lot for translating d2l to Vietnamese! We are doing a one major revise for d2l before printing it out. I'm wondering you are interested in having a chat. 

Best
Mu

**Comment by duythanhvn** [comment]
Hi @mli,

Thanks for contacting us, we have an interest in this matter. Please let us know how to get in touch for a more in-depth chat and what we'll discuss.

Kind regards,
Duy–Thanh Doan

**Comment by astonzhang** [comment]
Hi Duy-Thanh, we've scheduled the meeting with the email that you used to contact us earlier: contact@withthanh.com, at 8/12 9-9:30am PT. Would that work?

**Comment by duythanhvn** [comment]
Hi @astonzhang,

I was wondering if we could talk via email, I would like to have several project members able to discuss, we are in many parts of the world so it is quite difficult to choose a time to call.

**Comment by astonzhang** [comment]
That works. Let's chat via email then!

**Comment by duythanhvn** [comment]
@astonzhang Thank you, please get in touch via email at d2l-team@mlbvn.org.

cc @mlbvn/d2l, @mlbvn/advisors, @trGiang99
